<?php
return [
	'Albatross',
	'Angelfish',
	'Barnacle',
	'Barracuda',
	'Basking Shark',
	'Blue Whale',
	'Bottle Nosed Dolphin',
	'Catfish',
	'Clown Fish',
	'Crab',
	'Dolphin',
	'Electric Eel',
	'Elephant Seal',
	'Fish',
	'Giant Clam',
	'Great White Shark',
	'Grey Reef Shark',
	'Grey Seal',
	'Guppy',
	'Hammerhead Shark',
	'Hermit Crab',
	'Horn Shark',
	'Humpback Whale',
	'Jellyfish',
	'Killer Whale',
	'King Crab',
	'Leopard Seal',
	'Lionfish',
	'Lobster',
	'Manatee',
	'Manta Ray',
	'Minke Whale',
	'Moray Eel',
	'Nurse Shark',
	'Octopus',
	'Oyster',
	'Penguin',
	'Prawn',
	'Puffer Fish',
	'Scorpion Fish',
	'Sea Dragon',
	'Sea Lion',
	'Sea Otter',
	'Sea Slug',
	'Sea Squirt',
	'Sea Turtle',
	'Sea Urchin',
	'Seahorse',
	'Seal',
	'Shrimp',
	'Siamese Fighting Fish',
	'Snapping Turtle',
	'Sperm Whale',
	'Spiny Dogfish',
	'Sponge',
	'Squid',
	'Starfish',
	'Stellers Sea Cow',
	'Stingray',
	'Tiger Shark',
	'Whale Shark',
	'Zebra Shark',
];